name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: tmmethode-portfolio

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci --production
        npm ci --prefix client --production
        npm ci --prefix server --production

    - name: Build application
      run: |
        export GENERATE_SOURCEMAP=false
        npm run build
      env:
        CI: true
        NODE_ENV: production

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --source . \
          --project=${{ env.PROJECT_ID }} \
          --region=${{ env.REGION }} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=1Gi \
          --cpu=1 \
          --max-instances=10 \
          --port=8080 \
          --set-env-vars=NODE_ENV=production,PORT=8080 \
          --set-env-vars=MONGODB_URI=${{ secrets.MONGODB_URI }} \
          --set-env-vars=JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --set-env-vars=RATE_LIMIT_WINDOW_MS=900000 \
          --set-env-vars=RATE_LIMIT_MAX=100

    - name: Show service URL
      run: |
        echo "✅ Deployment complete!"
        echo "🌐 Service URL: https://${{ env.SERVICE_NAME }}-${{ env.REGION }}-${{ env.PROJECT_ID }}.a.run.app" 